### PR TITLE
improve Franca IDL support

### PR DESCRIPTION
**Pull request by jb090979**
Hi Kaloyan,

this branch contains all my changes. There a lot of change s and I hope that it is not too complex and you are able to understand my changes. Please check my changes.

it contains the following changes:

    support structured comments

    fix fidl import
        each namespace got a list of vissible namespaces corresponding the import directive. This list is used to determine the type references
        now it is possible ti import complex chain of fidl files
        this result in alot of changes im the processor code, espacially determing the symbol references. But I thin so it work as pyfranca user would expect.

    support hex intger values for cinstants and enumerations
        franca 0,9.2 do not support hex integer. I extend the franca syntax. As I read in the franca project. Newer Version also support hex integer values

    fix some smaller bug in fidl import
        now all path are normalized before using --> path compare works correctly

### CODE REVIEW

**Comment by jb090979** [comment]
Hi Kaloyan,

this branch contains all my changes. There a lot of change s and I hope that it is not too complex and you are able to understand my changes. Please check my changes.

it contains the following changes:

    support structured comments

    fix fidl import
        each namespace got a list of vissible namespaces corresponding the import directive. This list is used to determine the type references
        now it is possible ti import complex chain of fidl files
        this result in alot of changes im the processor code, espacially determing the symbol references. But I thin so it work as pyfranca user would expect.

    support hex intger values for cinstants and enumerations
        franca 0,9.2 do not support hex integer. I extend the franca syntax. As I read in the franca project. Newer Version also support hex integer values

    fix some smaller bug in fidl import
        now all path are normalized before using --> path compare works correctly

**Comment by zayfod** [comment]
Thanks for your work. You have progressed a lot.

I plan to take the changes but I will cherrypick and merge them one by one over a period of several days. This will allow me to understand the details.

Are you OK with this?

**Comment by jb090979** [comment]
that fine to me. Please let me know if my implementation of hex integer or structured comment doesn't match you conception.

**Comment by zayfod** [comment]
I just cherrypicked and integrated the hexadecimal literal support with minor modifications:

- I sticked to the original ast.IntegerValue but extended it with a _base_ property, similar to Python integers. The idea is to allow Franca processors to take advantage of the integer base property for code generation purposes.
- I added support for binary literals also as per examples in the Franca user guide
- I allowed the lexer to handle 0x, 0X, 0b, 0B prefixes as per examples in Franca user guide

Feedback is welcome.

**Comment by zayfod** [comment]
I integrated the structured comment support also. am quite excited about this - thanks @jb090979 !

- I cleaned up the way comments are used in the AST for more reuse
- I found a (hopefully) simpler way to make structured comments optional in the parser - again aiming les code duplication.
- structured comments are not supported for versions per the Franca user guide

Again, feedback is welcome.

**Comment by jb090979** [comment]
thanks for merging. 

Your additional changes are a good improvement. I like it.

**Comment by zayfod** [comment]
Just integrated the support for structured comments in fidl_dump.py - nice!

**Comment by zayfod** [comment]
I merged one more fix, related to nested imports and the relevant test cases. Many thanks for the temporary file creation - very handy!

I did not merge the whole commit 890e86ec061cffdfd0b5f30c7e285b1d8b325d81 as I am not entirely clear about its purpose. By design references should take care of namespace handling. If I have missed anything, let's handle it with separate issues and pull requests.

I am preparing the v0.4.0 release now with all your contributions.

**Comment by jb090979** [comment]
Thanks for merging. But there are still some bugs open. I will create serperate pull request for each bug the next days.

**Pull request closed without merging**
